document.querySelector("#selectAffirmation").addEventListener("click", function(){
    
    let affirmations = ["Plně věřím cestě, po které jsem se rozhodla jít a jsem otevřen/a tomu, co mi vesmír nabízí.",
"Rozhoduji se s lehkostí.",
"Jsem uvědomělá/ý a ve stresových situacích dělám dobrá rozhodnutí.",
"Beru na sebe jen povinnosti, které dokážu rozumně zvládnout.",
"Říkám ano pouze věcem, které opravdu chci dělat, a dovolím si říci ne, aniž bych se cítil/a provinile.",
"Dávám prostor své kreativní stránce.",
"Volný čas věnuji pouze věcem, které jsou pro mě důležité a dodávají mému životu radost a hodnotu a zbytek nechávám být.",
"Upřednostňuji čas v přírodě, protože podporuje mé fyzické a duševní zdraví.",
"Dělám rozhodnutí, díky kterým jsem každý den silnější, zdravější a živější.",
"Miluji své tělo.",
"Dnes chci vidět to, co chci vidět.",
"S každým malým rozhodnutím se posouvám ke svým cílům.",
"Jsem tak vděčná/ý za úžasná místa, kam mě moje tělo bere.",
"Miluji ten pocit, když jsem nabitá/ý energií po dobrém tréninku nebo náročné túře.",
"Jsem silná/ý a díky fyzickým výzvám se cítím naživu.",
"Cítím, že s každým dalším dobrodružstvím si věřím stále víc.",
"Jsem na sebe hrdá/ý, že upřednostňuji svou pohodu.",
"Každý den věnuji několik minut sama/sám sobě, meditaci, poděkování, uvědomění.",
"Nezabývám se tím, jaké názory na mě mají ostatní lidé.",
"Jsem vděčná/ý za všechno, co v životě mám a rozhodl/a jsem se zaměřit se na hojnost.",
"Jsem schopna/en dosáhnout všeho, co si zamanu.",
"Soustředím se na světlo a všechny dobré okamžiky na tomto světě.",
"Všechno dobře dopadne.",
"Miluji své tělo i svoji duši.",
"Mám radost ze života.",
"Věřím v sebe. Jsem silná/ý a nezávislá/ý.",
"Vše dělám nejlépe, jak umím.",
"Rostu a učím se každý den.",
"Mám život ve svých rukou.",
"Všechno je možné.",
"I toto pomine.",
"Jsem nohama na zemi a hlavou v oblacích.",
"Každý den mám bezbřehou hojnost.",
"Svět je v pořádku. Já jsem v pořádku.",
"Vybírám si to, co chci vidět.",
"Láska volá lásku. Spokojenost volá spokojenost.",
"Kým se dnes můžu stát?",
"Význam události neleží v události samotné, ale v tom, jak na ní zareaguji.",
"Staré musí odejít, aby mohlo přijít nové.",
"Jediná jistota je permanentní změna.",
"Vytváření života je TEĎ.",
"Víra v sebe je víra v Boha.",
"Problém nelze vyřešit na úrovni, na které vznikl.",
"Dnes sleduji svůj vlastní příběh.",
"Jedině klidná mysl je úrodným polem pro zasazování myšlenek.",
"Všechno je měnitelné.",
"Hledej a nalezneš. Zaklepej a dveře se otevřou.",
"Zklidni svou mysl.",
"Umím řešit problémy.",
"Jsem úspěšně na svojí cestě a vím, že moje vnitřní síla mě vede k úspěchu.",
"Jsem magnet na úspěch.",
"Vedu si skvěle.",
"Každý den jsem lepší o 1 %.",
"Dosahuji všech svých cílů snadno a rychle.",
"Vidím úspěch ve všem, co dělám.",
"Život je série nekonečna malých zázraků, a já si všímám každého z nich.",
"Co si o sobě myslím, je mnohem důležitější než to, co si o mně myslí ostatní.",
"Každý je génius, ale pokud budete posuzovat rybu podle její schopnosti vylézt na strom, bude celý svůj život žít s vědomím, že je neschopná. - Albert Einstein",
"Konám dobro a dobro se mi vrací.",
"Neočekávám nic a jsem vděčný/á za všechno.",
"Dovede tě to, co děláš dnes tam, kde chceš být zítra?",]
    
    let position = Math.ceil(Math.random()*affirmations.length-1)
    
    document.querySelector("#affirmationToday").textContent = affirmations[position]
    
    
    
    
})